version: '3.8'

services:
  app:
    image: app
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
      cache:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      MONGODB_URL: mongodb://mongodb:27017/online-gallery
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_REGION:
    networks:
      - app-network

  mongodb:
    image: mongo:7
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    container_name: cache
    image: redis:7.0-alpine
    restart: always
    command: redis-server
    volumes:
      - redis-data:/data/cache
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data: